apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-app
  name: redis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-app
  strategy: {}
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
        - image: redis
          name: redis
          resources: {}
status: {}
