apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: redis
  name: redis-service
spec:
  type: LoadBalancer
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
#    nodePort: 32002
  selector:
    app: redis-app
status:
  loadBalancer: {}
